### ISSUE TITLE
Missing class? CVP_LIVE_FILTER_QUERY

### ISSUE THREAD

**Issue by davidjosephhayes** [agileware/content-views-civicrm-data-processor#12]
This extensions is super cool!

I am playing around a bit with getting some CiviEvents to display in Content View free, but I ran into a 500 error referencing a missing class `CVP_LIVE_FILTER_QUERY`. Across this plugin and Content View, I only see one reference to this class. Maybe this class is only available in the Pro version?

```
[Wed Sep 30 15:49:55.479471 2020] [fcgid:warn] [pid 4927] [client x.x.x.x:18648] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Class 'CVP_LIVE_FILTER_QUERY' not found in /home/civicrm/public_html/wp-content/plugins/content-views-civicrm-data-processor/includes/class-cvc-query.php:66, referer: https://example.org/wp-admin/admin.php?page=content-views-add&id=7ab6320btw
[Wed Sep 30 15:49:55.479509 2020] [fcgid:warn] [pid 4927] [client x.x.x.x:18648] mod_fcgid: stderr: Stack trace:, referer: https://example.org/wp-admin/admin.php?page=content-views-add&id=7ab6320btw
[Wed Sep 30 15:49:55.479523 2020] [fcgid:warn] [pid 4927] [client x.x.x.x:18648] mod_fcgid: stderr: #0 /home/civicrm/public_html/wp-includes/class-wp-hook.php(287): Content_Views_CiviCRM_Query->alter_query_parameters(Array), referer: https://example.org/wp-admin/admin.php?page=content-views-add&id=7ab6320btw
[Wed Sep 30 15:49:55.479527 2020] [fcgid:warn] [pid 4927] [client x.x.x.x:18648] mod_fcgid: stderr: #1 /home/civicrm/public_html/wp-includes/plugin.php(206): WP_Hook->apply_filters(Array, Array), referer: https://example.org/wp-admin/admin.php?page=content-views-add&id=7ab6320btw
[Wed Sep 30 15:49:55.479530 2020] [fcgid:warn] [pid 4927] [client x.x.x.x:18648] mod_fcgid: stderr: #2 /home/civicrm/public_html/wp-content/plugins/content-views-query-and-display-post-page/includes/functions.php(666): apply_filters('pt_cv_query_par...', Array), referer: https://example.org/wp-admin/admin.php?page=content-views-add&id=7ab6320btw
[Wed Sep 30 15:49:55.479534 2020] [fcgid:warn] [pid 4927] [client x.x.x.x:18648] mod_fcgid: stderr: #3 /home/civicrm/public_html/wp-content/plugins/content-views-query-and-display-post-page/includes/functions.php(1211): PT_CV_Functions::view_process_settings('7ab6320btw', Array), referer: https://example.org/wp-admin/admin.php?page=content-views-add&id=7ab6320btw
[Wed Sep 30 15:49:55.479537 2020] [fcgid:warn] [pid 4927] [client x.x.x.x:18648] mod_fcgid: stderr: #4 /home/civicrm/public_html/wp-includes/class-wp-hook.php(287): PT_CV_Functions::ajax_callback_preview_request(''), referer: https://example.org/wp-admin/admin.php?page=content-views-add&id=7ab6320btw
[Wed Sep 30 15:49:55.479541 2020] [fcgid:warn] [pid 4927] [client x.x.x.x:18648] mod_fcgid: stderr: #5 /home/civicrm/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array), referer: https://example.org/wp-admin/admin.php?page=content-views-add&id=7ab6320btw
[Wed Sep 30 15:49:55.479544 2020] [fcgid:warn] [pid 4927] [client x.x.x.x:18648] mod_fcgid: stderr: #6 /home/civicrm/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array), referer: https://example.org/wp-admin/admin.php?page=content-views-add&id=7ab6320btw
[Wed Sep 30 15:49:55.479547 2020] [fcgid:warn] [pid 4927] [client x.x.x.x:18648] mod_fcgid: stderr: #7 /home/c in /home/civicrm/public_html/wp-content/plugins/content-views-civicrm-data-processor/includes/class-cvc-query.php on line 66, referer: https://example.org/wp-admin/admin.php?page=content-views-add&id=7ab6320btw
```

**Comment by agileware-justin** [comment]
Hi David,

Thanks for reaching out and also for your kind donation to support our team. I have assigned someone to review this issue and provide some advise. Agileware Ref: WPCV-37

Best wishes
Justin

**Comment by agileware-pengyi** [comment]
Hi David, the issue should be resolved after you update the plugin codebase. cdbb21accb683182edd932c48de6a6eb905bf758

**Comment by davidjosephhayes** [comment]
Awesome, thank you so much!

--
Regards,
Dave
(308) 660-4654

<https://blackbricksoftware.com/>

**Comment by agileware-pengyi** [comment]
Great. Closing
